"""Criar banco

Revision ID: 5ccebadded17
Revises: 
Create Date: 2025-07-09 12:41:11.296960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccebadded17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_origin', sa.Integer(), nullable=False),
    sa.Column('robot', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('action', sa.CHAR(length=1), nullable=True),
    sa.Column('screen', sa.CHAR(length=1), nullable=True),
    sa.Column('executable_path', sa.String(length=200), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('activation_file', sa.String(length=200), nullable=True),
    sa.Column('executable_name', sa.String(length=45), nullable=True),
    sa.Column('workbook', sa.String(length=200), nullable=True),
    sa.Column('spreadsheet_repository', sa.String(length=200), nullable=True),
    sa.Column('notified', sa.String(length=1000), nullable=True),
    sa.Column('activated_program1', sa.String(length=45), nullable=True),
    sa.Column('activated_program2', sa.String(length=45), nullable=True),
    sa.Column('robot_sequence', sa.Integer(), nullable=True),
    sa.Column('robot_user', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='statususer'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_robot',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'robot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_robot')
    op.drop_table('users')
    op.drop_table('robots')
    # ### end Alembic commands ###
