"""Criação da model Robo e atualizaçao de usuários

Revision ID: ba5760af3755
Revises: a98bf61b8a75
Create Date: 2025-07-07 13:31:54.520665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5760af3755'
down_revision: Union[str, Sequence[str], None] = 'a98bf61b8a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_origin', sa.Integer(), nullable=False),
    sa.Column('robot', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=1), nullable=True),
    sa.Column('screen', sa.String(length=1), nullable=True),
    sa.Column('executable_path', sa.String(length=200), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('activation_file', sa.String(length=200), nullable=True),
    sa.Column('executable_name', sa.String(length=45), nullable=True),
    sa.Column('workbook', sa.String(length=200), nullable=True),
    sa.Column('spreadsheet_repository', sa.String(length=200), nullable=True),
    sa.Column('notified', sa.String(length=1000), nullable=True),
    sa.Column('activated_program1', sa.String(length=45), nullable=True),
    sa.Column('activated_program2', sa.String(length=45), nullable=True),
    sa.Column('robot_sequence', sa.Integer(), nullable=True),
    sa.Column('robot_user', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot')
    )
    op.create_table('usuario_robo',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('robo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['robo_id'], ['robos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'robo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_robo')
    op.drop_table('robos')
    # ### end Alembic commands ###
